### ISSUE TITLE
Metrics error

### ISSUE THREAD

**Issue by Vetther** [EpicEricEE/JustMoney#12]
https://github.com/EpicEricEE/JustMoney/blob/c6608a5d6f4bed1c9da5b0d739b75066108a7fa4/src/main/java/de/epiceric/justmoney/JustMoney.java#L117-L119

```
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[JustMoney (1).jar:?]
at org.bstats.MetricsBase.(MetricsBase.java:104) ~[JustMoney (1).jar:?]
at de.epiceric.justmoney.bstats.Metrics.(Metrics.java:74) ~[JustMoney (1).jar:?]
at de.epiceric.justmoney.JustMoney.onEnable(JustMoney.java:117) ~[JustMoney (1).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-184]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-184]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.18.1.jar:git-Paper-184]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-184]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-184]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by EpicEricEE** [comment]
Should be fixed in v1.2.1 with b7df5d84. Sorry, I didn't actually test the plugin before releasing.
